### PR TITLE
Upgrade to prompt_toolkit 0.57.

### PR DESCRIPTION
**Pull request by jonathanslenders**
Upgrade from prompt_toolkit 0.52 to 0.57.

The changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG
If I have time, I can create also create a pull request for saws.

Feel free to not merge it if you have some doubts. I did some testing and it seems to work fine.

Jonathan

### CODE REVIEW

**Comment by jamesls** [comment]
Awesome thanks!  I'll take a look at this shortly.  IIRC the last time we looked at upgrading 0.52 -> 0.54 @donnemartin saw some cosmetic issues (https://github.com/awslabs/aws-shell/pull/78#issuecomment-165980787).  Let me just double check those are no longer an issue.

**Comment by donnemartin** [comment]
Thanks Jonathan!  

Yes James, I did see some issues with refresh, hopefully 0.57 fixes those.  Looks like you're already checking this out, I'll probably free up later this week if you'd like for me to take a look.

**Comment by donnemartin** [comment]
Unfortunately I'm still seeing the issues described [here](https://github.com/awslabs/aws-shell/pull/78#issuecomment-165980787).  

>I've tried several calls to cli redraws, cli reset, buffer reset, renderer reset, with no luck.

@jonathanslenders is there a call you can point me to properly force a refresh?  The following doesn't seem to do the trick in `app.py`:

```
def stop_input_and_refresh_cli(self):
    ...
    self.cli.request_redraw()
    ...
```

**Comment by jamesls** [comment]
Closing in favor of the 1.0.0 upgrade. (https://github.com/awslabs/aws-shell/pull/120)

**Pull request closed without merging**
